import './vendors/methods'
import './customers/methods'
import './users/server'
// import './branches/methods'
import './branches/server'
import './department/methods'
import './position/methods'
import './employeeType/methods'
import './employees/methods'
import './attendance/methods'
import './leaves/methods'